name: python

on:
  - push

env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  DJANGO_ENV: test
  DATABASE_URL: 'sqlite:///db.sqlite3'
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run pytest
        run: |
          make tests
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageCommand: make tests-with-coverage
          debug: true